package com.example.habitstreak.di

import android.content.Context
import androidx.room.Room
import androidx.work.WorkManager
import com.example.habitstreak.data.CompletionDao
import com.example.habitstreak.data.HabitDao
import com.example.habitstreak.data.HabitStreakDatabase
import com.example.habitstreak.data.MIGRATION_1_2
import com.example.habitstreak.data.QuoteApi
import com.example.habitstreak.data.QuoteDao
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

// Classes we don't own (Room, Retrofit, WorkManager) can't carry @Inject, so this module tells
// Hilt how to build them. Our own classes declare it themselves with @Inject on their constructors.
@Module
@InstallIn(SingletonComponent::class) // lives as long as the app process
object AppModule {

    @Provides
    @Singleton // one database instance for the whole app
    fun provideDatabase(@ApplicationContext context: Context): HabitStreakDatabase =
        Room.databaseBuilder(context, HabitStreakDatabase::class.java, "habitstreak.db")
            .addMigrations(MIGRATION_1_2)
            .build()

    // The DAOs are generated by Room and fetched from the database
    @Provides
    fun provideHabitDao(database: HabitStreakDatabase): HabitDao = database.habitDao()

    @Provides
    fun provideCompletionDao(database: HabitStreakDatabase): CompletionDao = database.completionDao()

    @Provides
    fun provideQuoteDao(database: HabitStreakDatabase): QuoteDao = database.quoteDao()

    @Provides
    @Singleton
    fun provideQuoteApi(): QuoteApi =
        Retrofit.Builder()
            .baseUrl("https://zenquotes.io/")
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(QuoteApi::class.java)

    @Provides
    @Singleton
    fun provideWorkManager(@ApplicationContext context: Context): WorkManager =
        WorkManager.getInstance(context)
}
